### ISSUE TITLE
请问大神能不能把云函数的数据库表结构给我们看一下呢？谢谢~

### ISSUE THREAD

**Issue by hjs557523** [LWJcoder/qiupihu#3]

**Comment by LWJcoder** [comment]
funnys 集合:
id           string     id
comment      array      评论
commentNum   int  		评论数
validStatus  int 		审核状态
validTime    time  		审核时间
shareNum     int   		分享数量
vote         int    	赞数量

**Comment by hjs557523** [comment]
> _No description provided._
